
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: matrix
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      hostNetwork: true  # 使用主机网络
      securityContext:   # 添加 Pod 级别的安全上下文
        runAsUser: 0   # 以 UID 991 运行
        runAsGroup: 0  # 以 GID 991 运行
        fsGroup: 0
      containers:
      - name: traefik
        image: traefik:latest
        ports:
        - containerPort: 7000
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: traefik-config
          mountPath: /etc/traefik/traefik.yml
        - name: dynamic-config
          mountPath: /etc/traefik/dynamic.yml
        - name: letsencrypt
          mountPath: /letsencrypt
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: traefik-config
        hostPath:
          path: /root/Matrix/K3s-volume/traefik/traefik.yml
          type: File
      - name: dynamic-config
        hostPath:
          path: /root/Matrix/K3s-volume/traefik/dynamic.yml
          type: File
      - name: letsencrypt
        hostPath:
          path: /root/Matrix/K3s-volume/traefik/letsencrypt
          type: DirectoryOrCreate
