services:
  synapse:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: synapse
    restart: unless-stopped
    mem_limit: 1024m
    ports:
      - "8008:8008"
      - "8448:8448"
    volumes:
      - ./Synapse/synapse:/data:rw 
    environment:
      - SYNAPSE_CONFIG_DIR=/data
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
#      - SYNAPSE_SERVER_NAME=synapse
#      - SYNAPSE_REPORT_STATS=no
#      - SYNAPSE_DB_HOST=synapse_db
#      - SYNAPSE_DB_USER=synapse_user
#      - SYNAPSE_DB_NAME=synapse
#      - SYNAPSE_DB_PASSWORD=your_password
    depends_on:
      - synapse-db
      - synapse-redis
      - mas
    networks:
      - matrix_net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8008/_matrix/static/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
#    command: generate

  synapse-db:
    image: postgres:latest
    user: "999:999"
    container_name: synapse-db
    restart: unless-stopped
    shm_size: "2g"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    volumes:
      - ./Synapse/synapse_db:/var/lib/postgresql/data:rw 
      - ./Synapse/synapse_db_conf/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5412:5432"
    networks:
      - matrix_net


  generic-worker-1:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: generic-worker-1
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/generic_worker_1.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 9001:9001
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis


  generic-worker-2:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: generic-worker-2
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/generic_worker_2.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 9011:9011
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis

  generic-worker-3:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: generic-worker-3
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/generic_worker_3.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 9012:9012
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis

  generic-worker-4:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: generic-worker-4
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/generic_worker_4.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 9013:9013
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis

  generic-worker-5:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: generic-worker-5
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/generic_worker_5.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 9014:9014
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis

  generic-worker-6:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: generic-worker-6
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/generic_worker_6.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 9015:9015
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis


  event-persister-1:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: event-persister-1
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/event_persister_1.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 9033:9033
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis

  event-persister-2:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: event-persister-2
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/event_persister_2.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 9034:9034
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis


  media-worker:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: media-worker
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/media_worker.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8083/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw
    environment:
      - SYNAPSE_WORKER=synapse.app.media_repository
    ports:
      - 9002:9002
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis


  federation-sender-1:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: federation-sender-1
    restart: unless-stopped
    mem_limit: 1024m
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/federation_sender_1.yaml"]
    healthcheck:
      disable: true
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    ports:
      - 9003:9003
    environment:
      SYNAPSE_WORKER: synapse.app.federation_sender
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis

  federation-sender-2:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: federation-sender-2
    restart: unless-stopped
    mem_limit: 1024m
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/federation_sender_2.yaml"]
    healthcheck:
      disable: true
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw 
    ports:
      - 9006:9006
    environment:
      SYNAPSE_WORKER: synapse.app.federation_sender
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis

  federation-sender-3:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: federation-sender-3
    restart: unless-stopped
    mem_limit: 1024m
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/federation_sender_3.yaml"]
    healthcheck:
      disable: true
    networks:
      - matrix_net
    volumes:
      - ./Synapse/synapse:/data:rw
    ports:
      - 9066:9066 
    environment:
      SYNAPSE_WORKER: synapse.app.federation_sender
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis

  push-worker:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: push-worker
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/push_worker.yaml"]
    volumes:
      - ./Synapse/synapse:/data:rw
    environment:
      - SYNAPSE_WORKER=synapse.app.pusher
    ports:
      - 9004:9004
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis
    networks:
      - matrix_net



  mas:
    image: ghcr.io/element-hq/matrix-authentication-service:latest
    user: "0:0"
#    image: ghcr.io/element-hq/matrix-authentication-service@sha256:776624188417652362e3f7c6727a9812d0b37ff690a74a3a5c671fe2f3cb82b0
    restart: unless-stopped
    container_name: mas
    ports:
      - 8100:8080
    volumes:
      - ./Synapse/mas_config:/data:rw
    networks:
      - matrix_net
    # FIXME: do we also need to sync the db?
    command: "server --config=/data/config.yaml"
    depends_on:
      - mas-db
      - synapse-redis

  mas-db:
    image: postgres:latest
    user: "999:999"
    container_name: mas-db
    restart: always
    environment:
      - POSTGRES_DB=mas 
      - POSTGRES_USER=synapse_user  
      - POSTGRES_PASSWORD=your_password  
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    volumes:
      - ./mas_db:/var/lib/postgresql/data  
    ports:
      - "5422:5432"  
    networks:
      - matrix_net
    depends_on:
      - synapse-redis

  synapse-redis:
    image: redis:6-alpine
    restart: unless-stopped
    container_name: synapse-redis
    ports:
      - "6378:6379"
    networks:
      - matrix_net

networks:
  matrix_net:
    external: true

