services:
  nginx-host:
    image: nginx
    container_name: nginx-host
    restart: always
    network_mode: "host"
    ports:
#      - "8777:8077"
      - "443:443"
    volumes:
      - ./config:/etc/nginx
      - ./well-known:/var/www
      - /root/Certs/Certbot:/etc/nginx/ssl
