---
apiVersion: v1
kind: Service
metadata:
  name: synapse-admin  #元名称
  namespace: ele-hq     #空间名称
spec:
  selector:
    app: synapse-admin    #app  名称
  ports:
  - port: 8111        #其他pod访问端口
    targetPort: 80    #容器端口
    nodePort: 38111    # 主机可访问端口
    protocol: TCP     # 明确指定协议（可选）
  type: NodePort
