version: '3.8'

services:
  synapse_nginx:
    image: nginx
    container_name: synapse_nginx
    restart: always
    ports:
      - "8007:8007"
      - "443:443"
    volumes:
      - ./config:/etc/nginx
      - ./well-known:/var/www
      - /root/Certs/Certbot/certs/archive:/etc/nginx/ssl
#      - ./nginx/logs:/var/log/nginx
    networks:
      - matrix_net
networks:
  matrix_net:
    external: true